name: Build release

on:
  # schedule:
  #   - cron: '0 */1 * * *'
  push:
  workflow_dispatch:


jobs:
  release_needed:
    runs-on: ubuntu-latest
    outputs:
      release_needed: ${{ steps.release_needed.outputs.release_needed }}
    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if release needed
        id: check
        run: |
          RELEASE_NEEDED=$(python main.py)
          echo ${RELEASE_NEEDED}
          echo "release_needed=${RELEASE_NEEDED}" >> $GITHUB_OUTPUT

  make_release:
    runs-on: ubuntu-latest
    needs: release_needed
    if: needs.release_needed.outputs.release_needed != 'false'
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get latest artifact
        run: |
          pip install requests
          python get_artifact.py ${{ steps.release_needed.outputs.release_needed }}

      # - uses: avakar/tag-and-release@v1
      #   with:
      #     tag_name: ${{ steps.build.outputs.tag_name }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: "Version ${{ steps.build.outputs.sha_short }}"
      #     tag_name: ${{ steps.build.outputs.tag_name }}
      #     files: rippled/rippled.tar.gz
