name: Build release if needed

on:
  # schedule:
  #   - cron: '0 */1 * * *'
  push:
  workflow_dispatch:


jobs:
  build_package:
    name: Build packages
    runs-on: ubuntu-latest
    # outputs:
    #   release_needed: ${{ steps.release_needed.outputs.release_needed }}
    # env:
    #   PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build package
        id: release_needed
        run: |
         touch cool.deb

      - name: Save artifact
        # if: steps.release_needed.outputs.release_needed != 'false'
        uses: actions/upload-artifact@v3
        with:
          name: cool.deb
          path: cool.deb

      # - name: Report all needed
      #   if: steps.release_needed.outputs.release_needed != 'false'
      #   run: |
      #     echo "git_rev: $(python main.py True)" >> $GITHUB_STEP_SUMMARY


      - name: Make_release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            cool.deb
